### ISSUE TITLE
Large Dataset to train discovery

### ISSUE THREAD

**Issue by Jazz2912** [IBM/watson-online-store#172]
Hello I am working on developing a similar application and looking for dataset in json/html format just like the way it is present in /data folder. Could you please point me to the complete dataset?

**Comment by dolph** [comment]
@Jazz2912 It looks to me like these documents were manually saved from Amazon product pages, so there's not a larger / more complete dataset than what is already in this repo (besides Amazon itself!). I'd recommend using the [Amazon Product Advertising API](https://docs.aws.amazon.com/AWSECommerceService/latest/DG/Welcome.html) to get up to date data in a more digestible format (i.e. JSON).

I'm closing this because it's not an issue, but feel free to leave additional comments. Thanks!
